# Module 8 — NumPy Broadcasting

---

# 1️⃣ Introduction to the Topic

Broadcasting is one of the most powerful features of NumPy.

Broadcasting allows NumPy to perform **mathematical operations between arrays of different shapes**.

Instead of manually resizing arrays, NumPy **automatically adjusts arrays** to make calculations possible.

Because of broadcasting:
- Code becomes shorter
- Programs run faster
- We avoid writing loops

Broadcasting is widely used in:
- Data analysis
- Machine learning
- Deep learning
- Image processing

---

# 2️⃣ Explanation of Concepts in Simple Language

## What is Broadcasting?

Broadcasting means **automatically expanding a smaller array so that it matches the size of a larger array**.

**Example**

Array
```text
[1 2 3]
```

Number
```text
5
```

Operation
```text
[1 2 3] + 5
```

NumPy internally converts it to
```text
[1 2 3]
[5 5 5]
```

Result
```text
[6 7 8]
```

So NumPy broadcasts the number **5 across the array**.

## Why Broadcasting is Useful

Without broadcasting we would need loops.

Example using loop:

In [ ]:
arr = [1,2,3]
result = []

for i in arr:
    result.append(i + 5)

print(result)

Using NumPy broadcasting:

In [ ]:
import numpy as np

arr = np.array([1,2,3])

# Broadcasting automatically adds 5 to each element
print(arr + 5)

---

# 3️⃣ Syntax

Broadcasting happens automatically during operations.

Common examples:

```python
array + number
array + array
array * number
array * array
```

---

# 4️⃣ Broadcasting Rules

NumPy follows three rules when broadcasting arrays.

### Rule 1 — Dimensions must match

If arrays have the same shape, operations occur element-wise.

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)

### Rule 2 — One dimension must be 1

If shapes differ, NumPy checks if one dimension equals **1**.
The smaller array is expanded automatically.

In [ ]:
import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6]])

vector = np.array([10,20,30])

# Vector is broadcast across rows
print(matrix + vector)

### Rule 3 — Incompatible shapes cause error

Example incompatible shapes:
```text
(3,3)
(2,3)
```

---

# 5️⃣ Code Examples

# Example 1 — Broadcasting with Scalar

In [ ]:
import numpy as np

arr = np.array([1,2,3])

result = arr + 5

print(result)

### Output
```text
[6 7 8]
```

# Example 2 — Broadcasting with Multiplication

In [ ]:
import numpy as np

arr = np.array([2,4,6])

result = arr * 3

print(result)

### Output
```text
[6 12 18]
```

# Example 3 — Two Arrays Broadcasting

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([10,20,30])

print(a + b)

# Example 4 — Broadcasting with 2D Array

In [ ]:
import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6]])

vector = np.array([10,20,30])

print(matrix + vector)

# Example 5 — Column Broadcasting

In [ ]:
import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6]])

column = np.array([[10],[20]])

print(matrix + column)

---

# 6️⃣ Real-World Example

### Student Marks with Bonus

In [ ]:
import numpy as np

marks = np.array([[70,75,80],
                  [65,72,78]])

bonus = np.array([5,5,5])

new_marks = marks + bonus

print(new_marks)

---

# 7️⃣ Important Tips

### Tip 1
Broadcasting works only when **dimensions are compatible**.

### Tip 2
Always check array shape using:
```python
array.shape
```

### Tip 3
Broadcasting is widely used in neural networks, image processing, and matrix operations.

---

# 8️⃣ Summary

In this module we learned:

- Broadcasting allows operations between arrays of different sizes
- NumPy automatically expands smaller arrays
- Broadcasting improves performance and readability
- Works with scalars, vectors, and matrices

It is heavily used in machine learning and deep learning.

---

# 9️⃣ Practice Questions

### Question 1
Create array `[2,4,6]` and add **10** using broadcasting.

### Question 2
Create matrix
```text
[[1,2,3],
 [4,5,6]]
```
Add vector `[10,20,30]`.

### Question 3
Multiply matrix
```text
[[2,3],
 [4,5]]
```
by scalar **3**.