# Module 7 — NumPy Array Joining and Splitting

---

# 1️⃣ Introduction to the Topic

In real-world data analysis, data often comes from **multiple sources**.
Sometimes we need to:
- **Combine arrays together**
- **Divide arrays into smaller parts**

NumPy provides powerful functions to handle this:

### Joining Arrays
- `concatenate()`
- `stack()`
- `hstack()`
- `vstack()`
- `dstack()`

### Splitting Arrays
- `split()`
- `hsplit()`
- `vsplit()`
- `dsplit()`

These functions are widely used in:
- Data preprocessing
- Machine learning datasets
- Data transformation

---

# 2️⃣ Explanation of Concepts in Simple Language

## Joining Arrays



Joining means **combining two or more arrays into one array**.

**Example:**

Array 1
```text
[1 2 3]
```
Array 2
```text
[4 5 6]
```
After joining:
```text
[1 2 3 4 5 6]
```

---

## Splitting Arrays



Splitting means **dividing a large array into smaller arrays**.

**Example:**

Original array
```text
[10 20 30 40]
```
After splitting:
```text
[10 20]   [30 40]
```

---

# 3️⃣ Syntax

### Concatenate
```python
np.concatenate((array1, array2), axis)
```

### Stack
```python
np.stack((array1, array2), axis)
```

### Horizontal Stack
```python
np.hstack((array1, array2))
```

### Vertical Stack
```python
np.vstack((array1, array2))
```

### Split
```python
np.split(array, number_of_parts)
```

---

# 4️⃣ Code Examples

---

# Example 1 — concatenate()
`concatenate()` joins arrays along an existing axis.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Pass a tuple of arrays to join them
result = np.concatenate((a, b))

print(result)

### Output
```text
[1 2 3 4 5 6]
```
### Explanation
Two arrays are combined into one **long array**.

---

# Example 2 — concatenate with 2D arrays

In [ ]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# Join arrays vertically along axis 0 (rows)
result = np.concatenate((a, b), axis=0)

print(result)

### Output
```text
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
```
### Explanation
`axis=0` means joining **rows**. (If we used `axis=1`, it would join columns).

---

# Example 3 — stack()
`stack()` joins arrays along a **new axis**.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack the 1D arrays to create a 2D array
result = np.stack((a, b))

print(result)

### Output
```text
[[1 2 3]
 [4 5 6]]
```
### Explanation
Arrays are stacked as **rows** in a new 2D matrix.

---

# Example 4 — hstack()



`hstack()` means **horizontal stack**.

In [ ]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

# Stack them side-by-side
result = np.hstack((a, b))

print(result)

### Output
```text
[1 2 3 4]
```
### Explanation
Arrays are joined **side by side**.

---

# Example 5 — vstack()



`vstack()` means **vertical stack**.

In [ ]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

# Stack them one on top of the other
result = np.vstack((a, b))

print(result)

### Output
```text
[[1 2]
 [3 4]]
```
### Explanation
Arrays are stacked **one above the other**.

---

# Example 6 — dstack()
`dstack()` stacks arrays along the **third dimension** (depth).

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack along the depth axis
result = np.dstack((a, b))

print(result)

### Output
```text
[[[1 4]
  [2 5]
  [3 6]]]
```
### Explanation
Creates a **3D array**.

---

# Example 7 — split()



`split()` divides an array into multiple equal parts.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

# Split the array into 2 sub-arrays
result = np.split(arr, 2)

print(result)

### Output
```text
[array([10, 20]), array([30, 40])]
```
### Explanation
The array is split into **2 equal parts**. Notice it returns a list of NumPy arrays.

---

# Example 8 — hsplit()



Splits an array **horizontally**.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

# Split horizontally into 2 equal matrices
result = np.hsplit(arr, 2)

print(result)

### Output
```text
[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]
```
### Explanation
The matrix is split **column-wise**.

---

# Example 9 — vsplit()



Splits an array **vertically**.

In [ ]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4],
                [5, 6],
                [7, 8]])

# Split vertically into 2 equal matrices
result = np.vsplit(arr, 2)

print(result)

### Output
```text
[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]
```
### Explanation
Matrix is split **row-wise**.

---

# 5️⃣ Explanation of Output

**Example:**
```python
np.concatenate((a,b))
```
**If:**
```text
a = [1 2 3]
b = [4 5 6]
```
**Output:**
```text
[1 2 3 4 5 6]
```
NumPy simply **joins the arrays sequentially**.

---

# 6️⃣ Real-World Example

### Example — Student Marks Dataset
Suppose marks from **two classes** are stored separately.

Class A: `[78 85 90]`
Class B: `[66 88 92]`

We want to combine them.

In [ ]:
import numpy as np

classA = np.array([78, 85, 90])
classB = np.array([66, 88, 92])

# Concatenate the two classes to create a single dataset
all_students = np.concatenate((classA, classB))

print(all_students)

### Output
```text
[78 85 90 66 88 92]
```
Now we have a **combined dataset for analysis**.

---

# 7️⃣ Important Tips / Common Mistakes

### Tip 1
Arrays must have **compatible shapes** for joining.

**Valid:** `(2×2) + (2×2)`
**Invalid:** `(2×2) + (3×2)` (if concatenating horizontally)

---

### Tip 2
Understand the axis parameter:

| Axis   | Meaning |
| ------ | ------- |
| axis=0 | rows    |
| axis=1 | columns |

---

### Tip 3
Use `np.concatenate()` for most standard joining operations. It is flexible and widely adopted.

---

# 8️⃣ Summary

In this module we learned:

### Joining Arrays
- `concatenate()`
- `stack()`
- `hstack()`
- `vstack()`
- `dstack()`

### Splitting Arrays
- `split()`
- `hsplit()`
- `vsplit()`
- `dsplit()`

These operations are used in:
- Data preprocessing
- Machine learning datasets
- Feature engineering

---

# 9️⃣ Practice Questions

### Question 1
Create two arrays `[1, 2, 3]` and `[4, 5, 6]`. Join them using **concatenate()**.

---

### Question 2
Stack arrays vertically using **vstack()**:
```text
[10, 20]
[30, 40]
```

---

### Question 3
Split the array `[5, 10, 15, 20]` into **2 equal parts**.