# Module 6 — NumPy Array Reshaping and Transformation

---

# 1️⃣ Introduction to the Topic

When working with data in NumPy, sometimes we need to **change the shape of arrays**.

For example:
- Convert a **1D array to a 2D array**
- Convert a **matrix into a single list**
- Change **rows into columns**

NumPy provides several functions for this:
- `reshape()`
- `flatten()`
- `ravel()`
- `transpose()`
- `resize()`
- `squeeze()`
- `expand_dims()`

These functions are very useful in **machine learning, image processing, and data analysis**.

---

# 2️⃣ Explanation of Concepts in Simple Language

## What is Reshaping?



Reshaping means **changing the structure (rows and columns) of an array without changing the data**.

**Example:**

1D array
```text
[1 2 3 4 5 6]
```

Convert to 2D array
```text
[[1 2 3]
 [4 5 6]]
```

The values remain the same, only the **shape changes**.

---

# 3️⃣ Syntax

### Reshape
```python
array.reshape(rows, columns)
```

### Flatten
```python
array.flatten()
```

### Ravel
```python
array.ravel()
```

### Transpose
```python
array.T
```

---

# 4️⃣ Code Examples

---

# Example 1 — reshape()

In [ ]:
import numpy as np

# Create a 1D array with 6 elements
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape it into 2 rows and 3 columns
new_arr = arr.reshape(2, 3)

print(new_arr)

### Output
```text
[[1 2 3]
 [4 5 6]]
```

### Explanation
Original array: `[1 2 3 4 5 6]`
Reshape into:
- 2 rows
- 3 columns

---

# Important Rule of reshape

Total elements must remain the same.

**Example:** 6 elements
Possible shapes: `2×3`, `3×2`, `1×6`, `6×1`
Not possible: `4×2` (8 elements needed)

---

# Example 2 — reshape with automatic dimension

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Using -1 tells NumPy to automatically calculate the number of columns
new_arr = arr.reshape(2, -1)

print(new_arr)

### Output
```text
[[1 2 3]
 [4 5 6]]
```
### Explanation
`-1` tells NumPy to **automatically determine the correct size** for that dimension based on the length of the array.

---

# Example 3 — flatten()



Flatten converts a **multi-dimensional array into a 1D array**.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Flatten the 2D array into a 1D array copy
flat = arr.flatten()

print(flat)

### Output
```text
[1 2 3 4 5 6]
```
### Explanation
The 2D array becomes a **single row array**.

---

# Example 4 — ravel()
`ravel()` also converts arrays to **1D**.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Ravel the 2D array into a 1D view
flat = arr.ravel()

print(flat)

### Output
```text
[1 2 3 4 5 6]
```
### Explanation
Similar to `flatten()`.

**Difference:**
- `flatten()` creates a **copy** (changes to the new array won't affect the original).
- `ravel()` creates a **view** (changes to the new array WILL affect the original).

This makes `ravel()` more memory efficient.

---

# Example 5 — transpose()



Transpose converts **rows into columns**.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Transpose the array using the .T attribute
print(arr.T)

### Output
```text
[[1 4]
 [2 5]
 [3 6]]
```
### Explanation
Original array has 2 rows and 3 columns. Transpose swaps `rows ↔ columns`.

---

# Example 6 — resize()
Resize changes the **size of the array** in place.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

# Resize the array in-place to 2x2
arr.resize(2, 2)

print(arr)

### Output
```text
[[1 2]
 [3 4]]
```
### Explanation
The array is reshaped into **2×2 matrix** directly.

---

# Example 7 — expand_dims()



Used to **add a new axis (dimension)**.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

# Add a new dimension at axis 0 (creating a row vector)
new_arr = np.expand_dims(arr, axis=0)

print(new_arr)

### Output
```text
[[1 2 3]]
```
### Explanation
Converted from **1D array to 2D array**.

---

# Example 8 — squeeze()
Removes **extra dimensions of size 1**.

In [ ]:
import numpy as np

# An array with 3 dimensions, but two of them are size 1
arr = np.array([[[1, 2, 3]]])

# Squeeze out the unnecessary size-1 dimensions
print(arr.squeeze())

### Output
```text
[1 2 3]
```
### Explanation
Removes unnecessary dimensions, leaving a simple 1D array.

---

# 5️⃣ Explanation of Output

**Example:**
```python
arr = np.array([1, 2, 3, 4, 5, 6])
arr.reshape(2, 3)
```
**Output:**
```text
[[1 2 3]
 [4 5 6]]
```
**Explanation:**
NumPy fills the matrix **row by row**.

---

# 6️⃣ Real-World Example

### Example — Student Marks Table
Suppose marks of **6 students** are stored in a 1D list.

In [ ]:
import numpy as np

marks = np.array([78, 85, 90, 66, 88, 92])

# We want to arrange marks in 2 rows and 3 columns to form a table
marks_matrix = marks.reshape(2, 3)

print(marks_matrix)

### Output
```text
[[78 85 90]
 [66 88 92]]
```
Now the data looks like a **table**, which is easier to analyze.

---

# 7️⃣ Important Tips / Common Mistakes

### Tip 1
Always ensure: `rows × columns = total elements`

**Example:** 6 elements
Valid shapes: `2×3`, `3×2`

---

### Tip 2
Use `-1` in reshape when unsure about dimension.
**Example:** `arr.reshape(3, -1)`

---

### Tip 3
Remember the difference between flattening techniques:

| Function  | Behavior     |
| --------- | ------------ |
| flatten() | creates copy |
| ravel()   | creates view |

`ravel()` is more **memory efficient**.

---

# 8️⃣ Summary

In this module we learned:
- **reshape()** changes array dimensions
- **flatten()** converts array to 1D
- **ravel()** converts array to 1D (memory efficient)
- **transpose()** swaps rows and columns
- **resize()** changes array size in place
- **expand_dims()** adds new dimension
- **squeeze()** removes extra dimensions

These operations are widely used in:
- Machine Learning
- Image Processing
- Data Transformation

---

# 9️⃣ Practice Questions

### Question 1
Create an array `[1, 2, 3, 4, 5, 6]`. Reshape it into a **3×2 matrix**.

---

### Question 2
Convert the following array into a **1D array** using flatten:
```text
[[10, 20],
 [30, 40]]
```

---

### Question 3
Transpose the matrix:
```text
[[1, 2],
 [3, 4],
 [5, 6]]
```