# Module 1 — Introduction to NumPy

---

# 1️⃣ Introduction to the Topic

**NumPy** stands for **Numerical Python**.

It is one of the most important Python libraries used for:
- Data Science
- Machine Learning
- Artificial Intelligence
- Scientific Computing
- Image Processing

NumPy helps us work with **large numerical data efficiently**.

Instead of using Python lists, NumPy provides a special object called:
**NumPy Array (ndarray)**

NumPy arrays are:
- Faster
- More memory efficient
- Support powerful mathematical operations

---

# 2️⃣ Explanation of Concepts in Simple Language

## What is NumPy?

NumPy is a **Python library used for numerical computing**.

It provides tools to:
- Work with **arrays**
- Perform **mathematical operations**
- Perform **linear algebra**
- Generate **random numbers**
- Perform **statistical calculations**

Think of NumPy as a **super powerful calculator for Python**.

---

## Why Do We Need NumPy?

Python lists are flexible but **slow when working with large numerical data**.

NumPy solves this problem by:
- Using **efficient memory storage**
- Using **vectorized operations**
- Using **compiled C code internally**

This makes NumPy **very fast**.

---

## Difference Between Python List and NumPy Array

| Feature                 | Python List      | NumPy Array      |
| ----------------------- | ---------------- | ---------------- |
| Speed                   | Slow             | Very Fast        |
| Memory                  | Uses more memory | Uses less memory |
| Mathematical operations | Not easy         | Very easy        |
| Data type               | Mixed allowed    | Same data type   |

---

# 3️⃣ Syntax (Basic Import)

Before using NumPy we must install and import it. 

### Installation
*Note: In a Jupyter Notebook, we use the `!` symbol to run terminal commands directly.*

In [1]:
# Install numpy using pip inside the notebook
!pip install numpy

### Importing NumPy
We use **np** as a shortcut (alias) to write NumPy functions easily.

In [2]:
# Import the numpy library and give it the standard alias 'np'
import numpy as np

---

# 4️⃣ Code Examples

## Example 1 — Creating a NumPy Array

In [3]:
import numpy as np

# Create a numpy array by passing a standard Python list
arr = np.array([10, 20, 30, 40])

# Print the newly created array
print(arr)

[10 20 30 40]


### Explanation
- `np.array()` creates a NumPy array
- We passed a list `[10, 20, 30, 40]`
- NumPy converts it into an **array object**

### Output
```
[10 20 30 40]
```
Notice that the numbers are printed **without commas** because it is a NumPy array.

---

## Example 2 — Mathematical Operation on Array

In [4]:
import numpy as np

# Create an array of numbers 1 to 4
arr = np.array([1, 2, 3, 4])

# Multiply every element in the array by 2 automatically
result = arr * 2

# Print the result
print(result)

[2 4 6 8]


### Explanation
Each element is multiplied by **2 automatically**.

### Output
```
[2 4 6 8]
```
NumPy performs **vectorized operations**, meaning operations apply to the whole array at once without writing a loop.

---

## Example 3 — Python List vs NumPy Speed Concept

### The Python List Way
When using standard Python lists, math operations require a loop.

In [5]:
# Standard Python lists
a = [1, 2, 3]
b = [4, 5, 6]

# Create an empty list to store the results
result = []

# Loop through the length of the list and add corresponding elements
for i in range(len(a)):
    result.append(a[i] + b[i])

print("Python List Result:", result)

Python List Result: [5, 7, 9]


### Output
```
Python List Result: [5, 7, 9]
```
This requires a **loop** to calculate.

---

### The NumPy Way
NumPy allows us to add the arrays directly together.

In [6]:
import numpy as np

# Create two NumPy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Add the two arrays directly together (Vectorization)
result = a + b

print("NumPy Array Result:", result)

NumPy Array Result: [5 7 9]


### Output
```
NumPy Array Result: [5 7 9]
```
No loop required → **cleaner and faster code**.

---

# 5️⃣ Explanation of Output

In NumPy:
```
[1 2 3]
```
This means:
`Array containing elements 1,2,3`

Unlike standard Python lists:
```
[1, 2, 3]
```
NumPy removes commas because it displays the data in **array format**.

---

# 6️⃣ Real-World Example

### Example — Student Marks Analysis

Imagine we have marks of students:
`Math scores = [78, 85, 90, 66]`

If we want to **add grace marks of 5** to every student.

### Without NumPy
We would need a loop to iterate over each student's score.

### With NumPy
We can do it in one single step.

In [7]:
import numpy as np

# Create an array of student marks
marks = np.array([78, 85, 90, 66])

# Add 5 grace marks to every student simultaneously 
updated_marks = marks + 5

# Print the new updated marks
print(updated_marks)

[83 90 95 71]


### Output
```
[83 90 95 71]
```
NumPy automatically adds **5 to every element**.

---

# 7️⃣ Important Tips / Common Mistakes

### Tip 1
Always import NumPy using the standard alias:

In [8]:
# Industry standard way to import numpy
import numpy as np

### Tip 2
NumPy arrays usually contain **same data type elements** (e.g., all integers or all floats).

**Example:**
`[1, 2, 3, 4]`

**Not recommended:**
`[1, "hello", 3]`

---

### Tip 3
NumPy is **optimized for numerical data**. Use **Pandas** for tabular (spreadsheet-like) data.

---

# 8️⃣ Summary

In this module we learned:
- NumPy stands for **Numerical Python**
- It is used for **fast numerical computation**
- NumPy provides **ndarray (array object)**
- NumPy arrays are **faster and more memory efficient**
- Mathematical operations on arrays are **very easy**
- NumPy is widely used in **Data Science, ML, AI**

---

# 9️⃣ Practice Questions

### Question 1
What is NumPy and why is it used?

---

### Question 2
Write a Python program to create a NumPy array containing numbers:
`10 20 30 40 50`

---

### Question 3
Write a NumPy program to multiply each element of an array by **3**.

**Example input:**
`[1, 2, 3, 4]`

**Expected output:**
`[3, 6, 9, 12]`