# 1️⃣ Introduction to the Topic

In NumPy, the most important object is the **NumPy Array**.

The NumPy array is called:
**ndarray (N-Dimensional Array)**

It is used to store **multiple values in a structured way** and allows **fast mathematical operations**.

Unlike Python lists, NumPy arrays:
- are **faster**
- use **less memory**
- allow **vectorized calculations**

In this module, we will learn:
- What is ndarray
- How to create arrays
- Array attributes
- Indexing
- Slicing

These are the **core foundations of NumPy**.

---

# 2️⃣ Explanation of Concepts in Simple Language

## What is ndarray?

**ndarray** means **N-Dimensional Array**.

It is a container used to store **elements of the same data type**.

**Example:**
`[10 20 30 40]`

This is a **1-dimensional array**.

NumPy arrays can have multiple dimensions:

| Dimension | Example                |
| --------- | ---------------------- |
| 1D        | [1 2 3 4]              |
| 2D        | Matrix                 |
| 3D        | Collection of matrices |



---

### Example of Dimensions

1️⃣ **1D Array**
```
[1 2 3 4]
```

2️⃣ **2D Array**
```
[[1 2 3]
 [4 5 6]]
```

3️⃣ **3D Array**
```
[
 [[1 2 3],
  [4 5 6]]
]
```

---

# 3️⃣ Syntax

Basic syntax to create a NumPy array:

In [1]:
import numpy as np

# Basic syntax: array_name = np.array(data)
arr = np.array([1, 2, 3, 4])

print("Basic Array:", arr)

Basic Array: [1 2 3 4]


---

# 4️⃣ Creating NumPy Arrays

NumPy provides multiple functions to create arrays.

Important functions:
- `np.array()`
- `np.zeros()`
- `np.ones()`
- `np.empty()`
- `np.arange()`
- `np.linspace()`

---

## 1. np.array()
Used to convert a **Python list into a NumPy array**.

In [2]:
import numpy as np

# Convert a list to an array
arr = np.array([10, 20, 30, 40])

print(arr)

[10 20 30 40]


### Output
```
[10 20 30 40]
```
### Explanation
- NumPy converts the list into an **array object**.

---

## 2. np.zeros()
Creates an array filled with **0s**.

### Syntax
`np.zeros(shape)`

In [3]:
import numpy as np

# Create an array of 5 zeros
arr = np.zeros(5)

print(arr)

[0. 0. 0. 0. 0.]


### Output
```
[0. 0. 0. 0. 0.]
```
### Explanation
Creates **5 elements with value 0**.

---

## 3. np.ones()
Creates an array filled with **1s**.

In [4]:
import numpy as np

# Create an array of 4 ones
arr = np.ones(4)

print(arr)

[1. 1. 1. 1.]


### Output
```
[1. 1. 1. 1.]
```

---

## 4. np.empty()
Creates an array with **random values from memory**.

In [5]:
import numpy as np

# Create an empty array of size 3 (values will be random garbage from memory)
arr = np.empty(3)

print(arr)

[0.00000000e+000 0.00000000e+000 4.84578638e-268]


### Explanation
It allocates memory but **does not initialize values**. Output will look like random tiny numbers (e.g., `[6.92e-310 6.92e-310 6.92e-310]`).

---

## 5. np.arange()
Creates an array with a **range of numbers**.

### Syntax
`np.arange(start, stop, step)`

In [6]:
import numpy as np

# Create an array from 1 to 9 (10 is excluded)
arr = np.arange(1, 10)

print(arr)

[1 2 3 4 5 6 7 8 9]


### Output
```
[1 2 3 4 5 6 7 8 9]
```

---

## 6. np.linspace()
Creates numbers **evenly spaced between two values**.

### Syntax
`np.linspace(start, stop, number_of_values)`

In [7]:
import numpy as np

# Generate 5 evenly spaced numbers between 1 and 10
arr = np.linspace(1, 10, 5)

print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


### Output
```
[ 1.    3.25  5.5   7.75 10.  ]
```
### Explanation
It generates **5 numbers evenly spaced between 1 and 10**.

---

# 5️⃣ Array Attributes

NumPy arrays have important attributes.

| Attribute | Meaning                     |
| --------- | --------------------------- |
| shape     | size of array               |
| size      | number of elements          |
| ndim      | number of dimensions        |
| dtype     | data type                   |
| itemsize  | memory used by each element |

In [8]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int64


### Output
```
Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int64
```
### Explanation
- `shape` → 2 rows, 3 columns
- `size` → total elements = 6
- `ndim` → 2 dimensional array
- `dtype` → integer type

---

# 6️⃣ Indexing

Indexing means **accessing elements using position numbers**.
Index starts from **0**.

## 1D Array Indexing

In [9]:
import numpy as np

arr = np.array([10, 20, 30, 40])

# Access the 1st element (Index 0)
print("Index 0:", arr[0])

# Access the 3rd element (Index 2)
print("Index 2:", arr[2])

Index 0: 10
Index 2: 30


### Explanation:
```
Index:  0  1  2  3
Array: [10 20 30 40]
```

---

## 2D Array Indexing

In [10]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Access element at Row 0, Column 1
print("Row 0, Col 1:", arr[0, 1])

Row 0, Col 1: 2


### Explanation:
```
[[1 2 3]
 [4 5 6]]
```
Row = 0, Column = 1 gives us `2`.

---

# 7️⃣ Slicing

Slicing is used to **extract multiple elements from an array**.

### Syntax
`array[start:end]`

In [11]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Extract elements from index 1 up to (but not including) index 4
print(arr[1:4])

[20 30 40]


### Output
```
[20 30 40]
```
Explanation: Index 1 to 3 is selected.

---

### 2D Slicing Example

In [12]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Select all rows (:), but only the column at index 1
print(arr[:, 1])

[2 5]


### Output
```
[2 5]
```
Explanation:
- `:` → all rows
- `1` → second column

---

# 8️⃣ Real-World Example

### Example — Temperature Data
Suppose we have temperature data for 5 days.

In [13]:
import numpy as np

temp = np.array([30, 32, 31, 29, 33])
print("All temps:", temp)

# Get temperature for the first 3 days
print("First 3 days:", temp[:3])

All temps: [30 32 31 29 33]
First 3 days: [30 32 31]


NumPy makes **data analysis easy**.

---

# 9️⃣ Important Tips / Common Mistakes

### Tip 1
Always check array dimensions using `arr.ndim` if you get an unexpected output.

---

### Tip 2
Use `arange()` carefully because the **stop value is excluded**.

In [14]:
import numpy as np

# Notice that 5 is NOT included in the output
print(np.arange(1, 5))

[1 2 3 4]


---

### Tip 3
Use `linspace()` when an **exact number of values are required**.

---

# 🔟 Summary

In this module we learned:
- NumPy array is called **ndarray**
- Arrays can be **1D, 2D, 3D**
- Ways to create arrays:
  - `array()`
  - `zeros()`
  - `ones()`
  - `empty()`
  - `arange()`
  - `linspace()`
- Important array attributes:
  - shape
  - size
  - ndim
  - dtype
- Indexing and slicing allow us to **access array elements easily**

---

# 1️⃣1️⃣ Practice Questions

### Question 1
Create a NumPy array containing:
`5 10 15 20`

---

### Question 2
Write a program to create an array of **10 zeros**.

---

### Question 3
Create a **2×3 NumPy array** and print:
- shape
- size
- ndim