# 🔢 NumPy for Beginners
### A Complete Hands-On Guide to Numerical Computing in Python

---

**NumPy** (Numerical Python) is the foundational library for scientific computing in Python.
It provides powerful **N-dimensional arrays**, fast mathematical operations, and utilities used
by almost every data science and ML library (Pandas, TensorFlow, scikit-learn, etc.).

### 📚 What You'll Learn
| Module | Topic |
|--------|-------|
| 1 | Installation & Import |
| 2 | Creating Arrays |
| 3 | Array Attributes |
| 4 | Indexing & Slicing |
| 5 | Array Reshaping |
| 6 | Basic Math Operations |
| 7 | Aggregate Functions |
| 8 | Broadcasting |
| 9 | Boolean Masking |
| 10 | Real-World Mini Project |

> 💡 **Tip:** Run each cell in order. Experiment by changing values to build intuition!

---
## 📦 Module 1: Installation & Import

NumPy comes pre-installed in most data science environments (Anaconda, Google Colab, Kaggle).
If you need to install it manually, run:
```bash
pip install numpy
```

By convention, NumPy is always imported as **`np`** — you'll see this everywhere in the Python ecosystem.

In [1]:
import numpy as np

# Always check the version to confirm it's installed
print('NumPy version:', np.__version__)
print('✅ NumPy imported successfully!')

NumPy version: 2.4.2
✅ NumPy imported successfully!


---
## 🏗️ Module 2: Creating Arrays

The core object in NumPy is the **`ndarray`** (N-dimensional array).
Unlike Python lists, NumPy arrays:
- Store elements of the **same data type** (homogeneous)
- Are **much faster** for numerical operations
- Support **vectorized operations** (no for-loops needed!)

### 2.1 — From Python Lists

In [3]:
# 1D Array — like a single row of numbers
scores = np.array([85, 92, 78, 95, 88])
print('1D Array (scores):', scores)

# 2D Array — like a table (rows x columns)
marks_table = np.array([[85, 92, 78],
                         [90, 88, 76],
                         [70, 95, 82]])
print('\n2D Array (marks table):')
print(marks_table)

# 3D Array — like multiple tables stacked (e.g., RGB image)
cube = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
print('\n3D Array shape:', cube.shape)

1D Array (scores): [85 92 78 95 88]

2D Array (marks table):
[[85 92 78]
 [90 88 76]
 [70 95 82]]

3D Array shape: (2, 2, 2)


### 2.2 — Built-in Array Creation Functions

NumPy provides handy functions to create common arrays without typing all values manually.

In [4]:
# zeros() — filled with 0s (great for initializing)
print('zeros(5)          :', np.zeros(5))
print('zeros((2,3))      :')
print(np.zeros((2, 3)))

# ones() — filled with 1s
print('\nones((2,4))       :')
print(np.ones((2, 4)))

# full() — filled with a specific value
print('\nfull((2,3), 7)    :')
print(np.full((2, 3), 7))

# eye() — identity matrix (diagonal = 1, rest = 0)
print('\neye(3)            :')
print(np.eye(3))

# arange() — like Python range(), but returns a NumPy array
print('\narange(0, 10, 2)  :', np.arange(0, 10, 2))  # start, stop, step

# linspace() — evenly spaced values between two numbers
print('linspace(0,1,6)   :', np.linspace(0, 1, 6))   # start, stop, num_points

zeros(5)          : [0. 0. 0. 0. 0.]
zeros((2,3))      :
[[0. 0. 0.]
 [0. 0. 0.]]

ones((2,4))       :
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

full((2,3), 7)    :
[[7 7 7]
 [7 7 7]]

eye(3)            :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

arange(0, 10, 2)  : [0 2 4 6 8]
linspace(0,1,6)   : [0.  0.2 0.4 0.6 0.8 1. ]


### 2.3 — Random Arrays

Random arrays are essential for simulations, testing algorithms, and initializing weights in ML models.

In [ ]:
np.random.seed(42)  # Set seed for reproducibility — results will be same every run

# Uniform random: values between 0 and 1
print('random.rand(3,3)  — uniform [0,1):')
print(np.random.rand(3, 3).round(2))

# Normal distribution: mean=0, std=1 (Gaussian)
print('\nrandom.randn(3,3) — standard normal:')
print(np.random.randn(3, 3).round(2))

# Random integers between low (inclusive) and high (exclusive)
print('\nrandom.randint(1, 100, size=(3,4)) — random ints:')
print(np.random.randint(1, 100, size=(3, 4)))

---
## 🔍 Module 3: Array Attributes

Before doing anything with an array, it's important to **inspect** it.
These attributes tell you everything about the array's structure.

In [ ]:
arr = np.array([[1.5, 2.3, 3.1],
                [4.7, 5.0, 6.8],
                [7.2, 8.9, 9.4]])

print('Array:')
print(arr)
print()

# Key attributes every beginner must know:
print(f'  ndim   (dimensions)  : {arr.ndim}')      # How many axes/dimensions
print(f'  shape  (rows, cols)  : {arr.shape}')     # Tuple of dimension sizes
print(f'  size   (total elems) : {arr.size}')      # Total number of elements
print(f'  dtype  (data type)   : {arr.dtype}')     # Type of stored elements
print(f'  nbytes (memory used) : {arr.nbytes} bytes')  # Memory consumption

### 3.1 — Data Types (dtype)

NumPy supports many numeric data types. Choosing the right dtype saves memory and improves performance.

| dtype | Description | Size |
|-------|-------------|------|
| `int8` / `int64` | Signed integers | 1–8 bytes |
| `float32` / `float64` | Floating point | 4–8 bytes |
| `bool` | True / False | 1 byte |
| `complex128` | Complex numbers | 16 bytes |

In [ ]:
# NumPy auto-detects dtype based on input
a_int   = np.array([1, 2, 3])
a_float = np.array([1.0, 2.5, 3.7])
a_bool  = np.array([True, False, True])

print(f'int array   dtype: {a_int.dtype}')    # int64
print(f'float array dtype: {a_float.dtype}')  # float64
print(f'bool array  dtype: {a_bool.dtype}')   # bool

# You can also specify dtype explicitly
a_f32 = np.array([1, 2, 3], dtype=np.float32)
print(f'\nExplicit float32: {a_f32}, dtype: {a_f32.dtype}')

# Converting (casting) between types
a_cast = a_float.astype(np.int32)
print(f'float64 → int32 : {a_cast}')  # decimals are truncated, not rounded!

---
## ✂️ Module 4: Indexing & Slicing

Accessing specific elements or sub-sections of an array is called **indexing** and **slicing**.
NumPy follows Python's 0-based indexing but adds powerful multi-dimensional access.

### 4.1 — 1D Indexing

In [ ]:
temps = np.array([22, 25, 19, 30, 28, 24, 21])  # Week temperatures
print('Temperatures:', temps)
print()

# Positive indexing (from start)
print(f'First day   [0]   : {temps[0]}')   # 22
print(f'Fourth day  [3]   : {temps[3]}')   # 30

# Negative indexing (from end)
print(f'Last day    [-1]  : {temps[-1]}')  # 21
print(f'Second last [-2]  : {temps[-2]}')  # 24

# Slicing: [start : stop : step]  (stop is EXCLUSIVE)
print(f'\nDays 2–4 [1:4]    : {temps[1:4]}')  # index 1,2,3
print(f'Every 2nd [::2]   : {temps[::2]}')   # 0,2,4,6
print(f'Reversed  [::-1]  : {temps[::-1]}')  # reverse

### 4.2 — 2D Indexing

For 2D arrays, indexing uses **[row, column]** syntax.

In [ ]:
# 3 students x 4 subjects: Math, Science, English, History
grades = np.array([[85, 90, 78, 92],
                    [70, 88, 95, 60],
                    [91, 75, 82, 87]])

print('Grades matrix (3 students × 4 subjects):')
print(grades)
print()

# Single element: [row, col]
print(f'Student 1, Science  [0,1]  : {grades[0, 1]}')   # 90
print(f'Student 3, English  [2,2]  : {grades[2, 2]}')   # 82

# Entire row
print(f'\nAll of Student 2    [1,:]  : {grades[1, :]}')  # entire row 1

# Entire column
print(f'All Math scores     [:,0]  : {grades[:, 0]}')   # entire col 0

# Sub-matrix (top-left 2x2)
print(f'\nTop-left 2×2 block  [:2,:2]:')
print(grades[:2, :2])

### 4.3 — Fancy Indexing

You can pass a **list of indices** to select multiple non-contiguous elements.

In [ ]:
fruits = np.array(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print('All fruits:', fruits)

# Select items at index 0, 2, 4 simultaneously
picked = fruits[[0, 2, 4]]
print('Picked (index 0,2,4):', picked)

# Works on 2D too — pick specific rows
print('\nGrades for Student 1 and 3 (rows 0 and 2):')
print(grades[[0, 2]])

---
## 🔄 Module 5: Array Reshaping

Reshaping lets you change the **shape** of an array without changing its data.
This is crucial in ML where models expect specific input shapes.

In [ ]:
# Start with a flat 1D array of 12 elements
flat = np.arange(1, 13)  # [1, 2, 3, ..., 12]
print('Original (1D):', flat)
print('Shape:', flat.shape)

# Reshape to 2D: 3 rows × 4 cols
grid_3x4 = flat.reshape(3, 4)
print('\nReshaped to (3,4):')
print(grid_3x4)

# Reshape to 2D: 4 rows × 3 cols
grid_4x3 = flat.reshape(4, 3)
print('\nReshaped to (4,3):')
print(grid_4x3)

# Reshape to 3D: 2 blocks × 3 rows × 2 cols
cube = flat.reshape(2, 3, 2)
print('\nReshaped to (2,3,2):')
print(cube)

In [ ]:
# Use -1 to let NumPy auto-calculate one dimension
auto = flat.reshape(6, -1)   # 6 rows, NumPy figures out cols = 2
print('reshape(6, -1) → shape:', auto.shape)  # (6, 2)

auto2 = flat.reshape(-1, 4)  # NumPy figures out rows = 3, 4 cols
print('reshape(-1, 4) → shape:', auto2.shape)  # (3, 4)

# Flatten: any shape → 1D
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print('\nOriginal shape:', matrix.shape)
print('After flatten() :', matrix.flatten())    # Returns a copy
print('After ravel()   :', matrix.ravel())      # Returns a view (more memory efficient)

### 5.1 — Transpose

Transpose **flips rows and columns** — rows become columns and vice versa.

In [ ]:
A = np.array([[1, 2, 3],
               [4, 5, 6]])

print('Original A (2×3):')
print(A)
print('Shape:', A.shape)

print('\nTranspose A.T (3×2):')
print(A.T)
print('Shape:', A.T.shape)

---
## ➕ Module 6: Basic Math Operations

NumPy operations are **element-wise by default** — no need to write loops!
This is called **vectorization** and it's much faster than Python loops.

In [ ]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([2,  4,  6,  8,  10])

print('a =', a)
print('b =', b)
print()

# Element-wise operations
print('a + b  :', a + b)   # Addition
print('a - b  :', a - b)   # Subtraction
print('a * b  :', a * b)   # Multiplication
print('a / b  :', a / b)   # Division (always returns float)
print('a // b :', a // b)  # Floor division (integer)
print('a % b  :', a % b)   # Modulo (remainder)
print('a ** 2 :', a ** 2)  # Power (each element squared)

In [ ]:
# Scalar operations: applied to every element
prices = np.array([100, 250, 180, 320, 75])

print('Original prices    :', prices)
print('After 10% discount :', prices * 0.90)
print('After 18% GST      :', (prices * 1.18).round(2))
print('Prices > 200       :', prices + 50)

### 6.1 — Universal Functions (ufuncs)

NumPy's **ufuncs** apply mathematical functions element-wise across arrays.
They are highly optimized (written in C) and much faster than Python's `math` module.

In [ ]:
x = np.array([0, 1, 4, 9, 16, 25])
print('x =', x)
print()

# Common ufuncs
print('sqrt(x)  :', np.sqrt(x))         # Square root
print('exp(x)   :', np.exp([0,1,2]).round(3))  # e^x (exponential)
print('log([1,e,e²]):', np.log([1, np.e, np.e**2]).round(2))  # Natural log
print('abs([-3,4,-5]):', np.abs([-3, 4, -5]))  # Absolute value

# Trigonometry (input in radians)
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
print('\nAngles (radians):', angles.round(3))
print('sin(angles)     :', np.sin(angles).round(3))
print('cos(angles)     :', np.cos(angles).round(3))

---
## 📊 Module 7: Aggregate Functions

Aggregate functions **summarize** an array into a single value (or a reduced array).
Use the **`axis`** parameter to aggregate along rows or columns.

In [ ]:
# 1D aggregation
data = np.array([4, 7, 2, 9, 1, 5, 8, 3, 6])
print('Data:', data)
print()

print(f'sum()      : {np.sum(data)}')       # Total
print(f'min()      : {np.min(data)}')       # Minimum value
print(f'max()      : {np.max(data)}')       # Maximum value
print(f'mean()     : {np.mean(data):.2f}')  # Average
print(f'median()   : {np.median(data)}')    # Middle value when sorted
print(f'std()      : {np.std(data):.2f}')   # Standard deviation (spread)
print(f'var()      : {np.var(data):.2f}')   # Variance
print(f'argmin()   : {np.argmin(data)}')    # INDEX of minimum
print(f'argmax()   : {np.argmax(data)}')    # INDEX of maximum
print(f'cumsum()   : {np.cumsum(data)}')    # Running total

In [ ]:
# 2D aggregation with axis parameter
# axis=0 → collapse rows (operate DOWN columns)  → result has shape (cols,)
# axis=1 → collapse cols (operate ACROSS rows)   → result has shape (rows,)

scores_2d = np.array([[85, 90, 78],   # Student A
                       [70, 88, 95],   # Student B
                       [91, 75, 82]])  # Student C

print('Scores matrix (students × subjects):')
print(scores_2d)
print()

# Mean of each subject (across all students): axis=0
print('Subject means (axis=0):', np.mean(scores_2d, axis=0))

# Mean of each student (across all subjects): axis=1
print('Student means (axis=1):', np.mean(scores_2d, axis=1))

# Overall max and min
print('\nOverall max:', np.max(scores_2d))
print('Overall min:', np.min(scores_2d))

---
## 📡 Module 8: Broadcasting

**Broadcasting** allows NumPy to perform operations on arrays of **different shapes** by
automatically "stretching" the smaller array to match the larger one.

### Broadcasting Rules:
1. If arrays differ in number of dimensions, pad with 1s on the **left**
2. Dimensions with size **1** are stretched to match the other
3. Sizes must be equal or one of them must be **1**

In [ ]:
# Example 1: Scalar + Array (simplest broadcast)
arr = np.array([1, 2, 3, 4, 5])
print('arr + 10 =', arr + 10)  # 10 is broadcast to [10,10,10,10,10]

# Example 2: 1D + 2D broadcast
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
row = np.array([10, 20, 30])   # Shape (3,)

print('\nMatrix + row vector (broadcasts across all rows):')
print(matrix + row)  # row is broadcast as [[10,20,30],[10,20,30],[10,20,30]]

# Example 3: Column vector broadcast
col = np.array([[100], [200], [300]])  # Shape (3,1)
print('\nMatrix + column vector (broadcasts across all cols):')
print(matrix + col)  # col is broadcast as [[100,100,100],[200,200,200],[300,300,300]]

# Real-world: Normalize each column (subtract column mean)
col_means = matrix.mean(axis=0)  # Shape (3,)
print('\nColumn means          :', col_means)
print('Mean-centered matrix  :')
print(matrix - col_means)

---
## 🎭 Module 9: Boolean Masking & Filtering

Boolean masking lets you **filter array elements** based on conditions — extremely useful
for data cleaning and analysis.

In [ ]:
# Daily temperatures for a month
daily_temps = np.array([22, 35, 18, 40, 15, 30, 28, 42, 19, 33,
                         26, 38, 21, 17, 36, 29, 23, 41, 16, 32])

# Step 1: Create a boolean mask
hot_mask = daily_temps > 30
print('Temperature data  :', daily_temps)
print('Mask (temp > 30)  :', hot_mask)

# Step 2: Apply mask to filter values
hot_days = daily_temps[hot_mask]
print('Hot days (>30°C)  :', hot_days)
print('Number of hot days:', len(hot_days))

# Shorthand (one step)
cold_days = daily_temps[daily_temps < 20]
print('\nCold days (<20°C) :', cold_days)

In [ ]:
# Compound conditions using & (AND), | (OR), ~ (NOT)
# Always wrap conditions in parentheses!

# Days between 25°C and 35°C (pleasant range)
pleasant = daily_temps[(daily_temps >= 25) & (daily_temps <= 35)]
print('Pleasant days (25–35°C):', pleasant)

# Days that are either very cold or very hot (extremes)
extreme = daily_temps[(daily_temps < 18) | (daily_temps > 40)]
print('Extreme temps (<18 or >40):', extreme)

# np.where: return values based on condition (like a vectorized if-else)
# np.where(condition, value_if_true, value_if_false)
labels = np.where(daily_temps > 30, 'Hot', 'Comfortable')
print('\nFirst 8 day labels:', labels[:8])

# Count how many elements satisfy a condition (True = 1, False = 0)
print('\nDays above 30°C:', np.sum(daily_temps > 30))

---
## 🚀 Module 10: Real-World Mini Project — Student Grade Analyzer

Let's put everything together! We'll analyze exam results for a class of students
using only NumPy operations.

**Dataset:** 10 students × 5 subjects (Math, Science, English, History, CS)

In [ ]:
np.random.seed(7)

students = ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan',
            'Fatima', 'George', 'Hina', 'Ivan', 'Jia']
subjects = ['Math', 'Science', 'English', 'History', 'CS']

# Simulate realistic marks (out of 100)
marks = np.random.randint(40, 100, size=(10, 5))

print('Student Marks Matrix (10 students × 5 subjects)')
print('-' * 55)
print(f'{"Student":<10}', '  '.join(f'{s:>8}' for s in subjects))
print('-' * 55)
for name, row in zip(students, marks):
    print(f'{name:<10}', '  '.join(f'{m:>8}' for m in row))

In [ ]:
# ── 1. Student Performance Summary ──────────────────────────────────────────
total_marks   = marks.sum(axis=1)          # Sum across subjects
avg_per_student = marks.mean(axis=1).round(1)
rank = total_marks.argsort()[::-1]         # Indices sorted by total (descending)

print('Student Performance (sorted by total marks):')
print(f'{"Rank":<6}{"Student":<12}{"Total":>8}{"Average":>10}')
print('-' * 40)
for i, idx in enumerate(rank, 1):
    print(f'{i:<6}{students[idx]:<12}{total_marks[idx]:>8}{avg_per_student[idx]:>10}')

# Top performer
top_idx = np.argmax(total_marks)
print(f'\n🏆 Top performer: {students[top_idx]} ({total_marks[top_idx]} marks)')

In [ ]:
# ── 2. Subject-wise Analysis ─────────────────────────────────────────────────
subject_avg = marks.mean(axis=0).round(1)  # Average across all students
subject_max = marks.max(axis=0)
subject_min = marks.min(axis=0)
subject_std = marks.std(axis=0).round(1)   # Higher std = more spread in scores

print('Subject-wise Statistics:')
print(f'{"Subject":<12}{"Avg":>8}{"Max":>6}{"Min":>6}{"Std":>8}')
print('-' * 42)
for subj, avg, mx, mn, std in zip(subjects, subject_avg, subject_max, subject_min, subject_std):
    print(f'{subj:<12}{avg:>8}{mx:>6}{mn:>6}{std:>8}')

# Hardest subject (lowest average)
hardest_idx = np.argmin(subject_avg)
print(f'\n📉 Hardest subject: {subjects[hardest_idx]} (avg {subject_avg[hardest_idx]})')

In [ ]:
# ── 3. Pass / Fail Analysis (passing = >= 50 in all subjects) ────────────────
pass_mask   = marks >= 50                       # Boolean: True where passed
all_passed  = pass_mask.all(axis=1)             # True if passed ALL subjects
passed_count = pass_mask.sum(axis=1)            # Number of subjects passed per student

print('Pass/Fail Report (pass mark = 50):')
print(f'{"Student":<12}{"Subjects Passed":>17}{"Overall Status":>16}')
print('-' * 48)
for name, cnt, passed in zip(students, passed_count, all_passed):
    status = '✅ PASS' if passed else '❌ FAIL'
    print(f'{name:<12}{cnt:>17}{status:>16}')

total_pass_students = all_passed.sum()
print(f'\n📊 Class pass rate: {total_pass_students}/{len(students)} students ({100*total_pass_students/len(students):.0f}%)')

# Students who need improvement (avg < 60)
needs_help = np.array(students)[avg_per_student < 60]
if len(needs_help):
    print(f'⚠️  Students needing extra support: {list(needs_help)}')

---
## 🎓 Summary Cheat Sheet

| Operation | Code Example | Description |
|-----------|-------------|-------------|
| Create array | `np.array([1,2,3])` | From Python list |
| Zeros | `np.zeros((3,4))` | 3×4 matrix of zeros |
| Range | `np.arange(0,10,2)` | `[0, 2, 4, 6, 8]` |
| Linspace | `np.linspace(0,1,5)` | 5 evenly spaced values |
| Shape | `arr.shape` | Tuple of dimensions |
| Reshape | `arr.reshape(3,4)` | Change shape (same data) |
| Transpose | `arr.T` | Flip rows ↔ columns |
| Slice 1D | `arr[1:5:2]` | Elements at index 1,3 |
| Slice 2D | `arr[0:2, 1:3]` | Rows 0-1, Cols 1-2 |
| Boolean filter | `arr[arr > 5]` | Elements greater than 5 |
| Conditional | `np.where(cond, a, b)` | Vectorized if-else |
| Aggregate | `np.mean(arr, axis=0)` | Column-wise mean |
| Math | `np.sqrt()`, `np.log()` | Element-wise ufuncs |

---
### 📖 Next Steps
- **Pandas** — Labeled data (DataFrames) built on top of NumPy
- **Matplotlib/Seaborn** — Visualizing NumPy arrays as charts
- **scikit-learn** — Machine learning using NumPy arrays
- **Linear Algebra** — `np.linalg` for dot products, matrix inverse, eigenvalues

> 💪 **Practice Challenge:** Try computing the correlation matrix of the marks dataset using `np.corrcoef(marks.T)` and find which pair of subjects has the highest correlation!